---
title: "模型简报"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
  fig.show = "asis", fig.showtext = TRUE)
```

# 校对

基准年实际值和模型值对比：

```{r BaseyearComp}
# 基准年实际值和模型结果比较
# 能耗总量和排放总量
md_emis_nrg_comp <- data.frame(
  datasrc = rep(c("实际", "模型"), 2), 
  item = rep(c("能源", "碳排放"), each = 2), 
  value = c(1300, round(tot_nrgsumce$BAU$energyconsump[1]/10000), 
            2348, round(tot_emissum$BAU$co2[1]))
)

# 煤油气电能耗占比
md_nrgprop_comp <- data.frame(
  datasrc = rep(c("实际", "模型"), each = 5), 
  item = rep(c("煤", "油", "气", "电", "其他"), 2),
  value = c(18.8, 27.7, 5.6, 47.1, 0.8, 
            round(as.numeric(tot_nrgpropaggfuel$BAU[1, -1])*100, 1))
)

md_nrgprop_comp$item <- 
  factor(md_nrgprop_comp$item, levels = c("煤", "油", "气", "电", "其他"))

# 煤油气电排放占比
md_emisprop_comp <- data.frame(
  datasrc = rep(c("实际", "模型"), each = 4), 
  item = rep(c("煤", "油", "气", "电"), 2),
  value = c(28.0,	32.3, 5.1, 34.6, 
            round(as.numeric(idx_emispropaggfuel[1, c(2:5)]), 1))
)

md_emisprop_comp$item <- 
  factor(md_emisprop_comp$item, levels = c("煤", "油", "气", "电", "其他"))

ggarrange(plotlist = list(
  ggplot(md_emis_nrg_comp, aes(x = item, y = value, fill = datasrc)) + 
    geom_bar(stat = "identity", position = "dodge") + 
    geom_text(aes(label = value), vjust = 1.3, 
              color = "white", position = position_dodge(.9)) + 
    labs(x = "总量"), 
  ggplot(md_nrgprop_comp, aes(x = item, y = value, fill = datasrc)) + 
    geom_bar(stat = "identity", position = "dodge") + 
    geom_text(aes(label = value), vjust = 1.3, 
              color = "white", position = position_dodge(.9)) + 
    labs(x = "能耗比例"), 
  ggplot(md_emisprop_comp, aes(x = item, y = value, fill = datasrc)) + 
    geom_bar(stat = "identity", position = "dodge") + 
    geom_text(aes(label = value), vjust = 1.3, 
              color = "white", position = position_dodge(.9)) + 
    labs(x = "排放比例")
), ncol = 1, common.legend = TRUE)
```

减煤情景电力和电力局预测推荐值对比：

```{r ElecComp}
md_elec_gov <- data.frame(
  year = c(2020:2026), 
  电力 = c(291.2, 315.0, 334.0, 353.0, 371.0, 388.0, 405.0), 
  src = "电力局")
md_elec_model <- tot_nrgaggfuel$BAU_SLC_DECOAL[c("year", "电力")]
md_elec_model <- md_elec_model[md_elec_model$year %in% md_elec_gov$year, ]
md_elec_model$电力 <- md_elec_model$电力/10000
md_elec_model$src <- "模型"
md_elec <- rbind(md_elec_gov, md_elec_model)
ggplot(md_elec) + geom_point(aes(year, 电力, color = src), alpha = 0.5, size = 2)
```

未来近期内天然气是否持续增长：

```{r FutGas}
ggplot(tot_nrgaggfuel$BAU_SLC_DECOAL) + 
  geom_line(aes(year, 天然气)) +
  scale_y_continuous(limits = c(0, 70000))
```

# 结果

各情景总排放和总能耗变化：

```{r FigNrgEmis}
ggarrange(plotlist = list(
      func_scompplot(tot_emissum[set_scalcs], "co2") + labs(y = "Emission"), 
      func_scompplot(tot_nrgsumce[set_scalcs], "energyconsump") + 
        labs(y = "Energy")), nrow = 1, common.legend = TRUE)
```

对应排放数据为：

```{r TotEmisData}
func_mrgcol(tot_emissum, "co2", c("BY", set_scalcs))
```

```{r TotEmisNrg}
knitr::kable(idx_peakyear, caption = "达峰年份")
```

各情景各部门峰值年份火柴图：

```{r PeakYear}
# 各情景各部门达峰年份火柴图
ggplot(melt(idx_peakyearsec, id = "scenarios"), 
           aes(x = value, y = variable)) + 
      geom_point(aes(color = variable), size = 2) + 
      geom_text(aes(label = value, hjust = -0.3), size = 3) + 
      geom_segment(aes(yend = variable, color = variable), xend = 0, size = 1) +
      xlim(c(2019, 2035)) + facet_wrap(~scenarios, ncol = 1) + 
      theme_bw()
```

一些关键指标图和数据表：

```{r FigKeyIndex}
# 作图查看各指标五年变化趋势
ggarrange(plotlist = list(
    ggplot(idx_output_long, aes(year, 高能耗传统行业增加值比例)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 低能耗传统行业增加值比例)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 新兴行业增加值比例)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 私家电动车比例)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 人均生活能耗五年变化率)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 清洁能源比例)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 能耗量)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 碳排放量)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 单位GDP能耗五年下降率)) + 
      geom_line(aes(color = scenario)), 
    ggplot(idx_output_long, aes(year, 单位GDP碳排放五年下降率)) + 
      geom_line(aes(color = scenario))), 
    nrow = 2, ncol = 5, common.legend = TRUE)
```

```{r TblIndex}
knitr::kable(idx_output_long[c("year", "scenario", "碳排放量", "能耗量", "单位GDP碳排放五年下降率", "单位GDP能耗五年下降率")], digit = 2, caption = "能耗和碳排放指标")
```

```{r TblIndIndex}
knitr::kable(idx_output_long[c("year", "scenario", "高能耗传统行业增加值比例", "低能耗传统行业增加值比例", "新兴行业增加值比例")], digit = 2, caption = "工业关键指标") 
```

```{r TblOtherIndex}
knitr::kable(idx_output_long[c("year", "scenario","私家电动车比例", "人均生活能耗", "人均生活能耗五年变化率")], digit = 2, caption = "其他行业关键指标") 
```

# 参数

各终端部门活动水平：

```{r ActivityLevel}
par(mfrow = c(3, 3))
plot(1, main = "农业")
func_history_project(agri_act[["BY"]], "agri", agri_act[["BAU_SLC_DECOAL"]], "area", style = "base")
plot(1, main = "其他行业")
for (i in list(ind_act, const_act, trans_act, com_act, hh_act)) {
  for (j in names(i[["BY"]])[names(i[["BY"]]) != "year"]) {
    func_history_project(i[["BY"]], j, i[["BAU_SLC_DECOAL"]], j, style = "base")
  }
}
```

各终端部门活动强度：先分终端部门，再分子部门，最后分能耗种类。在各终端部门的图中，不同子部门的图之间用带标题的单空心圆图（就是图中只有一个空心圆的那个图）分隔开。

农业：

```{r AgriNrgIntst}
# 农业
for (i in list(agri_nrgintst)) {
  par(mfrow = c(3, 3))
  for (j in names(i[["BY"]])[names(i[["BY"]]) != "year"]) {
    func_history_project(i[["BY"]], j, i[["BAU_SLC_DECOAL"]], j, style = "base")
  }
}
```

工业：

```{r IndNrgIntst}
# 工业
for (i in list(ind_nrgintst)) {
  for (j in names(i[["BY"]])) {
    par(mfrow = c(3, 3))
    plot(1, main = j)
    for (k in names(i[["BY"]][[j]])[names(i[["BY"]][[j]]) != "year"]) {
      plot(1, main = k)
      func_history_project(i[["BY"]][[j]], k, i[["BAU_SLC_DECOAL"]][[j]], k, style = "base")
    }
  }
}
```

建筑业：

```{r ConstNrgIntst}
# 建筑业
for (i in list(const_nrgintst)) {
  par(mfrow = c(3, 3))
  for (j in names(i[["BY"]])[names(i[["BY"]]) != "year"]) {
    func_history_project(i[["BY"]], j, i[["BAU_SLC_DECOAL"]], j, style = "base")
  }
}
```

服务业：

```{r ComNrgIntst}
# 服务业
for (i in list(com_nrgintst)) {
  for (j in names(i[["BY"]])) {
    par(mfrow = c(3, 3))
    for (k in names(i[["BY"]][[j]])[names(i[["BY"]][[j]]) != "year"]) {
      plot(1, main = k)
      func_history_project(i[["BY"]][[j]], k, i[["BAU_SLC_DECOAL"]][[j]], k, style = "base")
    }
  }
}
```

家庭：

```{r HhNrgIntst}
# 家庭
par(mfrow = c(3, 3))
plot(1, main = "electricity and coal")
func_history_project(hh_nrgintst[["BY"]]$household, "electricity", hh_nrgintst[["BAU_SLC_DECOAL"]]$hh_coal_elec, "electricity", style = "base")
plot(1, main = "lpg_users")
func_history_project(hh_nrgintst[["BY"]]$household, "rawcoal", hh_nrgintst[["BAU_SLC_DECOAL"]]$hh_coal_elec, "rawcoal", style = "base")

plot(1, main = "lpg_users")
func_history_project(hh_nrgintst[["BY"]]$lpg, "lpg", hh_nrgintst[["BAU_SLC_DECOAL"]]$hh_lpg, "lpg", style = "base")

plot(1, main = "gas_users")
func_history_project(hh_nrgintst[["BY"]]$gas, "gas", hh_nrgintst[["BAU_SLC_DECOAL"]]$hh_gas, "gas", style = "base")
```


